# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-27 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1500, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0438\u0441\u044c\u043c\u0430')),
                ('header', models.CharField(blank=True, max_length=150, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('sent_at', models.DateTimeField(blank=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438')),
                ('received', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='letters',
            field=models.ManyToManyField(related_name='clients', to='clients.EmailLetter'),
        ),
    ]
