# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-27 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20230727_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailletter',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438'),
        ),
    ]
