# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-27 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20230727_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailletter',
            name='header',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
