# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-28 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20230728_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailletter',
            name='footer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u0424\u0443\u0442\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u043f\u043e\u0447\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='emailletter',
            name='header',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='emailletter',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='emailletter',
            name='text',
            field=models.TextField(max_length=1500, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0438\u0441\u044c\u043c\u0430'),
        ),
    ]
