# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-29 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20230728_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailletter',
            old_name='received',
            new_name='is_opened',
        ),
    ]
