# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-30 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20230729_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailletter',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.Client'),
        ),
    ]
