# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-01 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20230730_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailletter',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters', to='clients.Client'),
        ),
    ]
